#
# NetworkPolicy Declaration
#
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.mops.name }}-access
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}
spec:
  podSelector:
    matchLabels:
      name: {{ .Values.mops.name }}
  ingress:
  - ports:
    - port: 3000
      protocol: TCP
