#
# ServiceAccount Declaration
#
apiVersion: v1
kind: ServiceAccount
  {{- if .Values.serviceAccount }}
  {{- if hasKey .Values.serviceAccount "automountServiceAccountToken" }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
  {{- end }}
  {{- end }}
metadata:
  name: {{ .Values.mops.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}