global:
  metrics:
    enabled: true
  logging:
    level: info
  oidcProviderPreset: ""
  oidcProvider:
    endpoints:
      authorization:
        redirectUrl: "https://st1.mo360mes-dev.app.corpintra.net/login"
      logout:
        additionalQueryParams:
          callback_uri: ""

tex-service-helm:
  replicas: "1"
  image:
    pullPolicy: IfNotPresent
  inbound:
    service:
      type: "ClusterIP"
      ports:
        - name: "http"
          port: 80
          targetPort: "http"

tex-caddy-helm:
  replicas: "1"
  image:
    pullPolicy: IfNotPresent
  annotations:
    ingress:
      kubernetes.io/ingress.class: "traefik"
      traefik.ingress.kubernetes.io/router.tls: "true"
      cert-manager.io/cluster-issuer: daimler-acme
  inbound:
    ingress:
      enabled: true
      rules:
        - host: st1.mo360mes-dev.app.corpintra.net
          http:
            paths:
              - path: /
                pathType: Prefix
                backend:
                  service:
                    name: tex-caddy
                    port:
                      name: http
      tls:
        - hosts:
            - st1.mo360mes-dev.app.corpintra.net
          secretName: st1.mo360mes-dev-tls-secret
    service:
      type: "ClusterIP"
      loadBalancer:
        ip: ""
        sourceRanges: []
      ports:
        - name: "http"
          port: 80
          targetPort: "http"
    tls:
      enabled: false
  extra:
    volumes:
      - name: tex-caddy-traefik-config-dynamic
        configMap:
          defaultMode: 420
          name: tex-caddy-traefik-config-dynamic
    volumeMounts:
      - mountPath: /config-dynamic
        name: tex-caddy-traefik-config-dynamic
    configmaps:
      - suffix: traefik-config-dynamic
        data:
          traefik-conf-dynamic.toml: |
            [http]
              [http.middlewares]
                [http.middlewares.stripPrefixRegexMiddleware]
                  [http.middlewares.stripPrefixRegexMiddleware.stripPrefixRegex]
                    regex = ["/[^/]*"]
  texCaddy:
    caddyfile:
      health:
        path: "/infra/lbtest1.html"
      tex:
        paths:
          - except: ["/favicon.ico", "/infra/lbtest1.html", "/rabbitmq", "/config-server"]
          - ui: ["/ui", "/testapp/ui"]
          - api: ["/api", "/testapp/api"]
      headers:
        - settings:
            - name: Strict-Transport-Security
              value: "max-age=31536000; preload;"
            - name: X-Frame-Options
              value: "DENY"
            - name: X-XSS-Protection
              value: "1; mode=block"
            - name: X-Content-Type-Options
              value: "nosniff"
            - name: Content-Security-Policy
              value: "frame-ancestors 'none'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; object-src 'none';"
            - name: X-Content-Security-Policy
              value: "frame-options 'deny';"
            - name: Referrer-Policy
              value: "no-referrer"
            - name: Server
              remove: true
      proxies:
        # URL of the target proxy
        - backend: "http://127.0.0.1:8000"
          path: "/*"
          settings:
            - |
              header_up Host {http.request.host}
              header_up X-Real-IP {http.request.remote}
              header_up X-Forwarded-For {http.request.remote}
              header_up X-Forwarded-Port {http.request.port}
              header_up X-Forwarded-Proto https
    cookies:
      tex:
        domain: "st1.mo360mes-dev.app.corpintra.net"
        path: "/"
        secure: true
        blockKey:
          fromString:
            active:
        hashKey:
          fromString:
            active:
      state:
        multiple:
          enabled: true
          expiry: 24h
    tokenMode: "COOKIE_HEADER"
    routes:
      logoutUrl: "/logout"
      loginUrl: "/login"
      customErrorPageUrl: "https://st1.mo360mes-dev.app.corpintra.net/testapp/static/error.html"
    tokenInfo:
      enabled: true
  traefik:
    forwardedHeaders:
      insecure: true
    providers:
      kubernetesIngress:
        namespaces: ["st1-mo360mes-dev"]
        ingressClass: "traefik-i3-access"
      file:
        filename: "/config-dynamic/traefik-conf-dynamic.toml"