#
# The separate ingressclasses clusterrole / binding is deployed for namespaced deployments, since it is required by Traefik
# and cannot be namespaced.
#
{{- if .Values.traefik.enabled }}
{{- if and .Values.rbac.enabled .Values.rbac.namespaced }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.resourceName }}-{{ .Release.Namespace }}-ingressclasses
  labels:
    {{- include "texCaddy.defaultLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.resourceName }}-{{ .Release.Namespace }}-ingressclasses
subjects:
  - kind: ServiceAccount
    name: {{ .Values.resourceName }}
    namespace: {{ .Release.Namespace }}
{{end}}
{{end}}