{{- if .Values.traefik.enabled }}
{{- if and .Values.rbac.enabled .Values.rbac.namespaced }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.resourceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "texCaddy.defaultLabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Values.resourceName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.resourceName }}
  namespace: {{ .Release.Namespace }}
{{end}}
{{end}}