{{- $_ := include "migrate.texCaddy" . -}}
{{- $context := . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.resourceName }}-caddyfile
  labels:
    {{- include "texCaddy.defaultLabels" . | nindent 4 }}
data:
  Caddyfile: |-
    {{- if .Values.texCaddy.caddyfileOverride }}
    {{- .Values.texCaddy.caddyfileOverride | nindent 4 }}
    {{- else }}
    {
      order tex before respond
      admin off
      http_port 9080
      {{- include "caddyfile.tls.globals" . | nindent 6 }}
    }

    (log_configuration) {
      log {
      {{- if .Values.texCaddy.caddyfile.accessLog }}
        {{- .Values.texCaddy.caddyfile.accessLog | nindent 8 }}
      {{- else }}
        level {{ .Values.global.logging.level }}
        format {{ .Values.global.logging.format }}  {
            time_key time
            time_format 2006-01-02T15:04:05.000Z
        }
      {{- end }}
      }
    }

    (configuration) {
      root * /dev/null

      {{- if .Values.texCaddy.caddyfile.health.path }}
      respond {{.Values.texCaddy.caddyfile.health.path}} 200
      {{ end }}

      import log_configuration

      tex {
        {{- range $line := .Values.texCaddy.caddyfile.tex.paths }}
        {{- range $texDefinitionKey, $paths := $line }}
        {{- if $paths }}
        {{ $texDefinitionKey }} {{ $paths | join " " }}
        {{- end }}
        {{- end }}
        {{- end }}

        opRedirectUrl {{ required "No redirect uri defined for OIDC Provider" .Values.global.oidcProvider.endpoints.authorization.redirectUrl | quote }}
        cookieDomain {{ required "Please specify .Values.texCaddy.cookies.tex.domain" .Values.texCaddy.cookies.tex.domain | quote }}
      }

      {{- include "caddyfile.headers" . | nindent 6 }}

      {{- range $proxy := .Values.texCaddy.caddyfile.proxies }}
      reverse_proxy {{ $proxy.path }} {{ required "Please add a backend-value to your proxy" $proxy.backend }} {
        {{- range $proxy.settings }}
        {{- . | nindent 8 }}
        {{- end }}
      }
      {{- end }}

      {{- if .Values.texCaddy.caddyfile.additionalCaddyfileDirectives }}
      {{ .Values.texCaddy.caddyfile.additionalCaddyfileDirectives | nindent 6 }}
      {{- end }}
    }

    {{- include "caddyfile.addressblocks" . | nindent 4 }} 

    :9091 {
      respond /health/* 200
      import log_configuration
    }

    {{- if .Values.global.metrics.enabled }}
    :9092 {
      metrics /metrics
      import log_configuration
    }
    {{- end }}

    {{ end }}
---
{{- if .Values.extra.configmaps }}
{{- range .Values.extra.configmaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $context.Values.resourceName }}-{{ .suffix }}
  labels:
    {{- include "texCaddy.defaultLabels" $context | nindent 4 }}
data:
{{- toYaml .data | nindent 2 }}
---
{{- end }}
{{- end }}
