{{- $_ := include "migrate.texCaddy" . -}}
{{- $_ := include "oidcProvider.presets" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.resourceName }}
  labels:
    {{- include "texCaddy.defaultLabels" . | nindent 4 }}
    {{- if .Values.labels.deployment }}
    {{- toYaml .Values.labels.deployment | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.annotations.deployment | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    {{- if .Values.updateStrategy }}
    {{- toYaml .Values.updateStrategy | nindent 4 }}
    {{- end }}
  minReadySeconds: {{ .Values.minReadySeconds }}
  selector:
    matchLabels:
      {{- include "texCaddy.defaultLabels" . | nindent 6 }}
      app-type: ingress-controller
      zone: ingress
  template:
    metadata:
      labels:
        {{- include "texCaddy.defaultLabels" . | nindent 8 }}
        app-type: ingress-controller
        zone: ingress
        {{- if .Values.labels.pod }}
        {{- toYaml .Values.labels.pod | nindent 8 }}
        {{- end }}
      annotations:
        # Leads to a change of the deployment when configmaps or secrets change, and the pods are redeployed
        checksum/traefik-config: {{ include (print $.Template.BasePath "/configmap-traefik.yaml") . | sha256sum }}
        checksum/caddy-config: {{ include (print $.Template.BasePath "/configmap-caddy.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
        {{- if .Values.annotations.pod }}
        {{- toYaml .Values.annotations.pod | nindent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      serviceAccountName: {{ .Values.resourceName }}
      {{- if .Values.extra.initContainers }}
      initContainers:
        {{- toYaml .Values.extra.initContainers | nindent 8 }}
      {{- end }}
      containers:
        {{- include "containers.traefik" . | nindent 8 }}
        {{- include "containers.caddy" . | nindent 8 }}
        {{- if .Values.extra.containers }}
        {{- toYaml .Values.extra.containers | nindent 8 }}
        {{ end }}

      {{- if .Values.image.pullSecrets }}
      imagePullSecrets:
      {{- toYaml .Values.image.pullSecrets | nindent 8 }}
      {{- end }}
      volumes:
        {{- include "volumes.caddy" . | nindent 8 }}
        {{- include "volumes.traefik" . | nindent 8 }}
        {{- include "tls.volumes" . | nindent 8 }}
        {{- include "cookie.keys.volumes" . | nindent 8 }}
        {{- if .Values.extra.volumes  }}
        {{- toYaml .Values.extra.volumes | trim | nindent 8 }}
        {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{- toYaml .Values.affinity | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}      
      {{- if .Values.nodeSelector }}
      nodeSelector:
      {{- range $key, $value := .Values.nodeSelector }}
        {{ $key }}: {{ $value | quote }}
      {{- end }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{- toYaml .Values.tolerations | nindent 8 }}
      {{- end }}