{{- $_ := include "migrate.texCaddy" . -}}
{{- if ne .Values.createConfigurationSecrets false }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.resourceName }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "texCaddy.defaultLabels" . | nindent 4 }}
type: Opaque
data:
  tex.client.id : {{ required "Please specify .Values.global.tokenExchange.credentials.clientID" .Values.global.tokenExchange.credentials.clientID | b64enc | quote }}
  tex.client.secret : {{ required "Please specify .Values.global.tokenExchange.credentials.clientSecret" .Values.global.tokenExchange.credentials.clientSecret | b64enc | quote }}
  op.client.id : {{ required "Please specify .Values.global.oidcProvider.clientCredentials.authCode.clientID" .Values.global.oidcProvider.clientCredentials.authCode.clientID | b64enc | quote }}
  op.client.secret : {{ required "Please specify .Values.global.oidcProvider.clientCredentials.authCode.clientSecret" .Values.global.oidcProvider.clientCredentials.authCode.clientSecret | b64enc | quote }}
  {{- if ne .Values.global.oidcProviderPreset "github" }}
  op.introspection.client.id : {{ .Values.global.oidcProvider.clientCredentials.tokenIntrospection.clientID | b64enc | quote }}
  op.introspection.client.secret : {{ .Values.global.oidcProvider.clientCredentials.tokenIntrospection.clientSecret | b64enc | quote }}
  {{- end }}
  {{- include "cookie.keys.secret" . | nindent 2 }}
  {{- range $secret := .Values.extra.secrets }}
  {{- if $secret.value }}
  {{ $secret.key }}: {{ $secret.value | b64enc | quote }}
  {{- else }}
  {{ $secret.key }}: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
---
{{ include "tls.secret" . }}
