#
# ServiceAccount Declaration
#
apiVersion: v1
kind: ServiceAccount
{{- if .Values.serviceAccount }}
{{- if hasKey .Values.serviceAccount "automountServiceAccountToken" }}
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- end }}
metadata:
  name: {{ .Values.resourceName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "texCaddy.defaultLabels" . | nindent 4 }}
