prometheus:
  additionalScrapeConfigs:
    enabled: true
    type: internal
    internal:
      jobList:
      - job_name: 'nginx-prometheus-exporter'
        static_configs:
         - targets: ['nginx-prometheus-exporter:9113']
      - job_name: 'cloudlflare-exporter-cloudflare-exporter'
        static_configs:
         - targets: ['cloudlflare-exporter-cloudflare-exporter:8080']