kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    kubeadmConfigPatches:
      - |
        kind: InitConfiguration
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: "ingress-ready=true"
    extraPortMappings:
      # http
      - containerPort: 80
        hostPort: 80
        protocol: TCP
        listenAddress: "127.0.0.1"
      # https
      - containerPort: 443
        hostPort: 443
        protocol: TCP
        listenAddress: "127.0.0.1"
      # postgresql
      - containerPort: 30000
        hostPort: 5432
        protocol: TCP
        listenAddress: "127.0.0.1"
      # rabbitmq
      - containerPort: 30001
        hostPort: 5672
        protocol: TCP
        listenAddress: "127.0.0.1"