apiVersion: v1
data:
   nginx.conf: |
    server {
    listen [::]:80;
    server_name localhost;

    location /nginx_status {
        stub_status on;
        access_log off;
        allow all;
    }
    }
kind: ConfigMap
metadata:
  name: nginx-config