apiVersion: v2
appVersion: 4.8.0
dependencies:
- name: tex-caddy-helm
  repository: ""
  version: 4.8.0
- name: tex-service-helm
  repository: ""
  version: 4.8.0
description: The goal of I³ Access is to integrate OIDC based central identity providers like GAS-OIDC or CIAM into DHC CaaS applications.
home: https://git.daimler.com/i3/i3-access
maintainers:
- email: i3.consulting@mercedes-benz.com
  name: i3
  url: https://pages.git.daimler.com/i3/welcome/
name: i3-access-helm
type: application
version: 4.8.0
