image:
  tag: 9.6.10

postgresqlUsername: postgres
postgresqlPassword: postgres

initdbScriptsConfigMap: postgresql-init-config

persistence:
  enabled: false

service:
  type: NodePort
  nodePort: 30000