{{- $_ := include "migrate.texService" . -}}
{{- $_ := include "oidcProvider.presets" . -}}
{{- $context := . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.resourceName }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "texService.defaultLabels" . | nindent 4 }}
data:
  tex-service-config.yaml: |
    serverPort: 8090

    tracing:
      ignoreEnvVariables: true
      serviceName: "{{.Values.resourceName}}.{{.Release.Namespace}}"
      {{- toYaml .Values.global.tracing | nindent 6 }}

    metrics:
      enabled: {{ .Values.global.metrics.enabled }}

    logging:
      {{- toYaml .Values.global.logging | nindent 6 }}
    
    profiling:
      {{- toYaml .Values.texService.profiling | nindent 6 }}

    tokenExchangeCredentials:
      - clientID:
          fileRef: "/secrets/tex.client.id"
        clientSecret:
          fileRef: "/secrets/tex.client.secret"
    cache:
      {{- toYaml .Values.texService.cache | nindent 6 }}

    jwt:
      {{- include "jwt.configmap" . | nindent 6 }}

    mappers:
      {{- include "mappers.configmap" . | nindent 6 }}
      {{- if .Values.texService.mappers }}
      {{- toYaml .Values.texService.mappers | nindent 6 }}
      {{- end }}
---
{{- if .Values.extra.configmaps }}
{{- range .Values.extra.configmaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $context.Values.resourceName }}-{{ .suffix }}
  labels:
    {{- include "texService.defaultLabels" $context | nindent 4 }}
data:
{{- toYaml .data | nindent 2 }}
---
{{- end }}
{{- end }}