image:
  registry: registry.app.corpintra.net
  repository: mbfs.powertrain/rabbitmq
  pullSecrets:
    - harbor-pullsecret
  tag: 3.9.13-debian-10-r0
  pullPolicy: IfNotPresent

loadDefinition:
  enabled: true
  existingSecret: load-definition
extraConfiguration: |
  load_definitions = /app/load_definition.json
  management.path_prefix = /rabbitmq/

auth:
  username: guest
  password: guest
  erlangCookie: cookie

persistence:
  enabled: false

service:
  type: NodePort
  nodePort: 30001

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  path: /rabbitmq/
  hostname: st1.mo360mes.localhost