commonLabels: {}

statefulsetLabels: {}

podLabels:
  app: mo360mes
  namespace: st1-mo360mes-dev
  env: dev

replicaCount: 1

metrics:
  enabled: true

extraPlugins: "rabbitmq_auth_backend_ldap rabbitmq_prometheus"

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: 9419
  prometheus.io/rx-scrape-every-30s: "true"

image:
  registry: registry.app.corpintra.net
  repository: mbfs.powertrain/rabbitmq
  pullSecrets:
    - harbor-pullsecret
  tag: 3.9.13-debian-10-r0
  pullPolicy: IfNotPresent

loadDefinition:
  enabled: true
  existingSecret: load-definition
extraConfiguration: |
  load_definitions = /app/load_definition.json
  management.path_prefix = /rabbitmq/

auth:
  username: mbfsuser
  password: dauk3sdacley8DIRK!un
  erlangCookie: cookie

# mbfsadmin password:  hjWErARasOeLBXMiPHi

persistence:
  enabled: true
  storageClass: cinder

serviceAccount:
  create: true

rbac:
  create: true

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: "traefik"
  path: /rabbitmq/
  hostname: st1.mo360mes-dev.app.corpintra.net
